name: Build APK

on:
  push:
    branches: [main]  # You can change this if your default branch is different

jobs:
  build:
    name: Build Kivy APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential git zip unzip openjdk-17-jdk python3-pip \
          libffi-dev libssl-dev libpng-dev \
          libgl1-mesa-dev libgles2-mesa-dev \
          libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
          libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
          zlib1g-dev

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install cython virtualenv buildozer

    - name: Build APK with Buildozer
      run: |
        buildozer android debug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: kivy-apk
        path: bin/*.apk
